### PR TITLE
Use environment variable for SLACK_NAME, not config yaml

### PR DESCRIPTION
**Pull request by doismellburning**
My goal: to remove the need to fork and edit files to run destalinator
yourself

### CODE REVIEW

**Comment by doismellburning** [comment]
I don't know if this heads in a direction y'all would like (hence I've only done so for the config item most likely to be changed) but as a user it sure is nice to not need to maintain my own *divergent* fork (even if it's only the tiniest of divergences)

**Comment by doismellburning** [comment]
Note, it shouldn't break compatibility for existing users (though I've only verified that manually)

**Comment by royrapoport** [comment]
If you make it so we choose an environment variable FIRST, then use config file, then you won't make the rest of us have to change our invocations.  Can you change config.py?

**Comment by doismellburning** [comment]
Not sure I follow, sorry... Are you saying you think I *have* broken compat?

**Comment by royrapoport** [comment]
Nevermind, logic is solid.  Dropping the line from configuration.yaml will cause current users to have to fix the issue (either add it or define the env variable), but that's a minimal cost, IMO.

**Comment by doismellburning** [comment]
It's ok, I added that line back ;)

**Comment by doismellburning** [comment]
And thanks!

**Pull request merged**
