### PR TITLE
Add Docker build steps to the Travis build

### PR DESCRIPTION
**Pull request by TheConnMan**
Auto-deploy a new Docker images when a git tag is pushed. You'll need to create the Docker Hub repo `randsleadershipslack/destalinator` and add the env vars `DOCKER_USERNAME` and `DOCKER_PASSWORD` to the Travis build.

It will end up looking like https://hub.docker.com/r/theconnman/destalinator.

### CODE REVIEW

**Comment by zeckalpha** [comment]
Awesome!

I wrote the dockerfile to help with running the tests locally, does it make sense to include them in the dockerfile if Travis is running both Python versions at the same time as building it?

Would this only run on the master branch?

–
Kyle Marek-Spartz

**Comment by TheConnMan** [comment]
The tests would still run on every PR and commit, but the Docker image push only happens on git tag pushes (of which you currently have none). That's what the `on: tags: true` portion of the Travis file does. That way you only get image pushes on real releases, not on every commit or even every push to `master`.

**Comment by TheConnMan** [comment]
As far as running the test locally the Dockerfile has been very helpful, all my local dev was within the container as I don't have a valid Python 3 dev environment (nor want one), but I do intend to run this in AWS ECS so a prebuilt, public Docker image will be very helpful.

**Comment by zeckalpha** [comment]
Will this break anything if it is merged prior to getting the DockerHub repo set up?

**Comment by zeckalpha** [comment]
I suppose not, because it would wait for a tag...

**Comment by TheConnMan** [comment]
You got it, the deploy only happens on tags.

**Pull request merged**
