### PR TITLE
Add notes on required libraries

### PR DESCRIPTION
**Pull request by ichthyos**
Ran into a bit of trouble trying to get this to work until I realized I should be using Python 2. Comments welcome.

### CODE REVIEW

**Comment by dlovitch** [comment]
@ichthyos Would you mind sharing what didn't work for you in py3?

**Comment by ichthyos** [comment]
So it's totally possible I was doing something silly but I set up a py3 virtualenv, ran `warner.py`, and it tried to warn every channel instead of just the ones without activity within the `warn_threshold`.

**Comment by ichthyos** [comment]
Btw, happy to open an issue on that and close this one if the intent is for these scripts to work with py3!

**Comment by dlovitch** [comment]
So I also setup a py3 virtualenv (3.5.2), installed the dependencies, then ran `warner.py` on a test Slack of mine. I did get one error (`TypeError: a bytes-like object is required, not 'str'` which I can fix by changing line 129 in `destalinator.py` to `and b":dolphin:" not in x.get("text").encode('utf-8', 'ignore')`), but I am not seeing the same behavior re: warning every channel.

I tested with and without `DESTALINATOR_ACTIVATED` set.

Which version of Python are you using? That's the only thing I can think of off the bat that might cause an issue.

**Comment by ichthyos** [comment]
Did some interactive troubleshooting with @dlovitch that didn't really lead anywhere so I'm adding info here for posterity. 😃 

I was using Python 3.5.2, and here are the libraries installed in the virtual env:
```$ pip install -r requirements.txt
Collecting APScheduler==3.0.5 (from -r requirements.txt (line 1))
  Using cached APScheduler-3.0.5-py2.py3-none-any.whl
Collecting requests==2.9.1 (from -r requirements.txt (line 2))
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting PyYAML==3.11 (from -r requirements.txt (line 3))
Requirement already satisfied: six in ./.venv/lib/python3.5/site-packages (from APScheduler==3.0.5->-r requirements.txt (line 1))
Collecting pytz (from APScheduler==3.0.5->-r requirements.txt (line 1))
  Using cached pytz-2016.10-py2.py3-none-any.whl
Collecting tzlocal (from APScheduler==3.0.5->-r requirements.txt (line 1))
Installing collected packages: pytz, tzlocal, APScheduler, requests, PyYAML
Successfully installed APScheduler-3.0.5 PyYAML-3.11 pytz-2016.10 requests-2.9.1 tzlocal-1.3```

**Comment by ichthyos** [comment]
Updated to remove py3 note -- seems to work with recent patches.

**Pull request merged**
