### PR TITLE
Additional env vars

### PR DESCRIPTION
**Pull request by TheConnMan**
Add a couple additional environment variables for ease of development and Flagger configurability.

### CODE REVIEW

**Comment by zeckalpha** [comment]
Was the flagged disabled to avoid a bug, or do you not plan on using it? I've started to move people to the reacji-channeller instead, I hope to deprecate the flagger.

–
Kyle Marek-Spartz

**Comment by TheConnMan** [comment]
No bug, just didn't plan on using it.

**Comment by zeckalpha** [comment]
Okay, now that #122 was merged... can we use the central Config object for these? ;)

**Comment by TheConnMan** [comment]
Definitely for `FLAGGER_DISABLED`, I'm cool adding in `RUN_ONCE` for consistency, it's just a dev thing though, not as much a "config" thing.

**Pull request merged**
